### ISSUE TITLE
Save-buttons are not working properly after first download

### ISSUE THREAD

**Issue by luechtian** [jannikbuhr/ShinyLipids#56] opened 2020-08-11 14:44 UTC
Next downloads are the same plots as the first one (for pdf's as well as .rds-files).

**Comment by jannikbuhr** [comment] 2020-08-13 20:29
I can confirm this. Working on a fix now.

**Comment by jannikbuhr** [comment] 2020-08-13 21:15
Turns out my thought to be very elegant solution to create all the download handlers didn't work due to lazy evaluation. The dowload handler would be created only after the first thing was downloaded and then wasn't reacting to changes in the thing to download. Should be fixed now:

**Closed** 2020-08-13 21:16 UTC
Labels: bug
